### ISSUE TITLE
Example app is not shown in the share sheet iOS 

### ISSUE THREAD

**Issue by wildsurfer** [KasemJaffer/receive_sharing_intent#82]
Thanks for the plugin! I'm trying to add receiving of sharing intent to my app. It works well on Android but icon never showed on my iOS device (both bare metal and simulator). 

I thought that probably I'm missing something so I took code form example and tried to start it. Result is the same -- it works on Android but not on iOS.

I tried this solution (https://github.com/KasemJaffer/receive_sharing_intent/issues/20) but no luck :(

```
/Users/kuzma/flutter/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.2 at /Users/kuzma/flutter/flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kuzma/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhoneOlolo (mobile) • e4733c552a5c06b324acafd2fed2a88721b8c3fb • ios • iOS 13.6
    • iPhone 11 (mobile)   • 25D43CEF-0EF6-40E4-B11C-EE0E1C3DA5F7     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
Process finished with exit code 0
```

**Comment by mustafarenkci** [comment]
@wildsurfer Same issue. Any solution?

**Comment by wildsurfer** [comment]
> @wildsurfer Same issue. Any solution?

Not yet :(

**Comment by ingmarcur** [comment]
@wildsurfer Same issue here...

**Comment by ingmarcur** [comment]
@mustafarenkci @wildsurfer 
I was able to make the example work.

- changed appleid user in both targets
- changed bundlename
- changed group name for both targets

--> The following made the app appear in the share sheet:
* The example ships with build versions for Runner at IOS 8.0 while the share extension ships with 12.4?
- Change the build version of Runner to 12.4 

Hope this helps.

@KasemJaffer thanks for building this.

**Comment by aaronfg** [comment]
@ingmarcur I tried your solution in my project. Changed Runner to 12.2 and kept the extension at 12.4.

Still don't see the app in the share sheet. ☹️

**Comment by ingmarcur** [comment]
@aaronfg sorry.. typo.. both build versions should be the same. Also on my own project I had xcode complaining about not being able to create public placeholder and I "fixed" that by applying a tip on stackoverflow "Build Phases and on "Embedded App Extensions" check the "Copy only when installing" checkbox". However, that interferes as well and you have to fix that error some other way.

**Comment by aaronfg** [comment]
I set both to 12.4 and it's still not working. 

Also, I did have to check that "copy when installing" checkbox or else the app wouldn't build at all.

And now, I can only build from xcode. Building from vscode is busted. Not sure what's up with that.

So many issues with this library I'm starting to think maybe I just skip ios support entirely.

**Comment by ingmarcur** [comment]
Yeah I went nuts on it yesterday full day. But it works it's the xcode part which is making it difficult. 

Eventually I fixed it by making the example work first and then repeat it in my own project.

Maybe good news is that the plugin placeholder only is happening on simulator but works on real iphone. 

- In my project I fixed the placeholder error by
-- making sure the bundle names are correct. Than both targets on manual signing after that enable signing with your id again. (Some xcode bug that doesn't notice the change)
- Deleting derived data dir: per https://developer.apple.com/forums/thread/89065

Don't forget to edit the swift controller in the shared extension directory.

**Comment by mustafarenkci** [comment]
I found a solution. 

1. Step - Uncheck "Copy only when installing"
![Ekran Resmi 2020-09-01 11 02 58](https://user-images.githubusercontent.com/5858308/91823978-b2cd0a00-ec42-11ea-9c6f-ce70c255bd68.png)

2. Step - Set "Debug" both of these lines.
![image](https://user-images.githubusercontent.com/5858308/91823858-8adda680-ec42-11ea-8316-30c5287260ae.png)

**Comment by wildsurfer** [comment]
Thanks guys! I was finally able to run it. Here is a list of complete steps to make it working:

1. `git clone` and open `example` folder in Android Studio
2. Open `pubspec.yml` and press `Pub Get` button
3. `Tools -> Flutter -> Open iOS` module in Xcode
4. `TARGETS -> Runner -> Signing & Capabilities`. Choose your team and change Bundle Identifier to something unique
5. Uncheck existing group and create new one that matches new Bundle Identifier
6. `TARGETS -> Sharing Extension -> Signing & Capabilities`. Choose new group (you may need to push refresh button in Add Groups section)
7. Go to `TARGETS -> Runner -> Deployment` Info and change target from 8.0 to 12.2
8. Go to `PROJECT -> Runner -> Configurations` and set `Debug -> Runner -> Share Extension` to `Debug`
9. Quit Xcode
10. `rm -rf ~/Library/Developer/Xcode/DerivedData`
11. Edit bundle name in `Sharing Extension/ShareViewController.swift`
12. `Tools -> Flutter -> Flutter Clean`
13. Go back to Android Studio, choose your iOS device and run your app

**Comment by VimeshLunagariya** [comment]
Not wrking....

**Comment by derekpankaew** [comment]
I followed all the steps in @wildsurfer and @mustafarenkci's above and it still doesn't work :/
